### ISSUE TITLE
This selector is the bane of my existance

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/RunestoneComponents#99]
```css
 .container  .section >*:not(.section) {
	max-width: 500pt;
	margin-left: auto;
	margin-right: auto;
}
```

@ericsonga @TommyHubbard 

Anything we can do to get rid of this rule, but still get the text margins nice would probably simplify our lives in many ways!

Bonus points for giving an explanation of the meaning of that nasty selector!

**Comment by TommyHubbard** [comment]
That rule was in there from the beginning, and basically selects everything/all children (*)‎ in the div with the class section EXCEPT the div itself.

I figured it was set up like this for a reason so as opposed to changing it‎, I figured I'd use additional classes to extend or override some of those properties if necessary.   That can be done by defining the same property (IE, max-width) and appending the !important rule at the end of the value.

The reason I added changed width to max-width was so the width wouldn't be fixed.   It would decrease and increase (not to exceed 500pts) when necessary.

I didn't think I had checked this part in, as I found it to be problematic.   My latest change has it as a width (not max-width) and a percentage value.   I believe it's 60% but will double check later.   With the percentage value, it increases and decreases like it should.

Tommy

Sent from my BlackBerry 10 smartphone.
From: Brad Miller
Sent: Thursday, October 22, 2015 5:42 PM
To: RunestoneInteractive/RunestoneComponents
Reply To: RunestoneInteractive/RunestoneComponents
Cc: Tommy Hubbard
Subject: [RunestoneComponents] This selector is the bane of my existance (#99)


```css
 .container  .section >*:not(.section) {
        max-width: 500pt;
        margin-left: auto;
        margin-right: auto;
}
```

@ericsonga @TommyHubbard

Anything we can do to get rid of this rule, but still get the text margins nice would probably simplify our lives in many ways!

Bonus points for giving an explanation of the meaning of that nasty selector!


---
Reply to this email directly or view it on GitHub:
https://github.com/RunestoneInteractive/RunestoneComponents/issues/99
